// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_8Pc9CWNlbuy7ld3VXlUgO_Nnvec6UzA',
    appId: '1:842673728422:web:1e44a30d1b785f3782bd67',
    messagingSenderId: '842673728422',
    projectId: 'montugo-e20be',
    authDomain: 'montugo-e20be.firebaseapp.com',
    storageBucket: 'montugo-e20be.firebasestorage.app',
    measurementId: 'G-W2W2XHDXRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJi0lLeGiOFfOmoqrDr2T1eTUE2O_OHWg',
    appId: '1:842673728422:android:f60082e3a116fbab82bd67',
    messagingSenderId: '842673728422',
    projectId: 'montugo-e20be',
    storageBucket: 'montugo-e20be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7irRiq-5eJgTpRuhihkVOFYPWoIiiRHs',
    appId: '1:842673728422:ios:663698ca4e87f07082bd67',
    messagingSenderId: '842673728422',
    projectId: 'montugo-e20be',
    storageBucket: 'montugo-e20be.firebasestorage.app',
    iosBundleId: 'com.example.montugo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7irRiq-5eJgTpRuhihkVOFYPWoIiiRHs',
    appId: '1:842673728422:ios:663698ca4e87f07082bd67',
    messagingSenderId: '842673728422',
    projectId: 'montugo-e20be',
    storageBucket: 'montugo-e20be.firebasestorage.app',
    iosBundleId: 'com.example.montugo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_8Pc9CWNlbuy7ld3VXlUgO_Nnvec6UzA',
    appId: '1:842673728422:web:c2acdce40bd6107b82bd67',
    messagingSenderId: '842673728422',
    projectId: 'montugo-e20be',
    authDomain: 'montugo-e20be.firebaseapp.com',
    storageBucket: 'montugo-e20be.firebasestorage.app',
    measurementId: 'G-C6GWQ7P9JK',
  );
}
